apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibG9ib3Z2aXQiLCJwYXNzd29yZCI6ImdocF9UUnhRVGllYThSMmYxeHlWTTdhRUhMMGIxbHBndVoyQlE5Q1EiLCJlbWFpbCI6ImxvYm92LnZpdGFsaXlAZ21haWwuY29tIiwiYXV0aCI6ImJHOWliM1oyYVhRNloyaHdYMVJTZUZGVWFXVmhPRkl5WmpGNGVWWk5OMkZGU0V3d1lqRnNjR2QxV2pKQ1VUbERVUT09In19fQ==
type: kubernetes.io/dockerconfigjson
